version: '3'
services: 
  webapp: 
    container_name: message-destruct
    restart: always
    build: .
    ports: 
      - '80:80'
    volumes:
      - ./public_html/:/var/www/html
      - ./:/var/www/
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: self_destruct
    ports:
      - "3308:3306"